### ISSUE TITLE
Automatically open the extension modal

### ISSUE THREAD

**Issue by raster21** [block-wallet/extension#235]
Current behavior:

- user clicks on "connect wallet" on a standard dApp front-end
- Block Wallet shows a blue (1) on its icon to indicate a state change
- user clicks on the Block Wallet extension icon to make the modal visible

Expected behavior:

- user clicks on "connect wallet" on a standard dApp front-end
- Block Wallet shows a blue (1) on its icon to indicate a state change AND automatically makes the modal visible.

The blue (1) ticker is very easy to miss (happened to me a few times), so toggleing the modal will make it clear to the user that some user input is awaited.

**Comment by julianariel** [comment]
hey @raster21 , thanks a lot for your submission!

BlockWallet supports the expected behavior you're describing when interacting with dApps. For example, performing a swap on Uniswap:
![chrome_gZ4HTpFrwh](https://user-images.githubusercontent.com/11839151/204352942-1f32229e-bca3-4091-b0d3-60e90f188c75.gif)

This is why I'd like to ask if you can provide us with a bit more context about the tests you've made. Would be good to know:
- OS and Browser you're using
- dApps you've interacted with and encountered this issue
- did you have any BlockWallet tab opened? onboarding, seed phrase import, hardware wallet connect.

Thank you in advance for your response

**Comment by raster21** [comment]
Thanks for your quick response! You are right, I restarted my browser and could not reproduce the behavior. For reference I tried Block Wallet on Chromium (v107.x). I will close this and re-open if I manage to get the same behavior again.
