### ISSUE TITLE
Issue: Wallet shows that transactions are still pending after they've gone through.

### ISSUE THREAD

**Issue by idktobehonestt** [block-wallet/extension#248]
After you've sent any kinds of transactions they still show as Pending in the Chrome wallet extension. If you check any explorer (bscscan, etherscan) then you can see that the transactions have gone through long ago yet the wallet shows otherwise. You're free to do more transactions but they'll stack on each other.

To reproduce the behavior:
1. Go to either one of these DEXes
- https://poocoin.app/swap
- https://app.uniswap.org/#/swap?chain=mainnet
2. Try buying any of the tokens, most likely USDC would be the best for testing.
3. Then check your wallet on either etherscan or bscscan, you should see that the transaction has gone through but wallet shows that the transactions are still pending.

Expected behavior:
Once the transcation is finished it also shows as completed within the wallet.

Was able to get rid of the pending txs within the wallet by reinstalling it but once I made transactions again the same issue happened.

 - Windows 11
 - Chrome
 - Version 108.0.5359.94 (Official Build) (64-bit)

It would also be great if it would be possible to clear the current txs within the wallet if this issue appears same as you can use the option to "Reset wallet" on Metamask which deletes only your transaction history.

![Screenshot 2022-12-03 025241](https://user-images.githubusercontent.com/88051346/205414242-fd0d045f-8ba4-494a-a9da-ddfee0a11252.png)

**Comment by idktobehonestt** [comment]
Not sure what caused the issue but now it has disappeared and works as intended but the whole evening yesterday it had these problems.

**Comment by AidenNguyen142** [comment]
I also have the same problem, 1 txn will be stuck for a very long time (~10 mins) and once it comes thru all of the pending txns come thru at once, like flushing the toilet XD

**Comment by julianariel** [comment]
hey @idktobehonestt @AidenNguyen142 ,

We've been analysing this and found out that one of our RPC providers had some issues at the time you had these problems. After that, we switched providers, ran different tests and didn't reencounter this bug. Can you please confirm for us that this didn't happen again to you either?

If so, we'll proceed to close the issue.

Thanks!

**Comment by julianariel** [comment]
hey @AidenNguyen142 ,

unfortunately, in the case of zkSync Alpha, we don't have a way of ensuring nodes' performance because it is a testnet and even if we wanted to, none of our node providers supports it yet. We're using their public nodes, which have proven to be slow and faulty sometimes, which is understandable due to their in-development status.

However, there are some adjustments we can make to the intervals that we use to fetch transaction status as long as we see that their node improves. We'll keep analysing this, but in case you have problems with any of the mainnets we support, we'll proceed to close the issue.

thanks for your support!
