### ISSUE TITLE
Site not working after installing blockwallet

### ISSUE THREAD

**Issue by ryptodevc** [block-wallet/extension#250]
**Describe the bug**
I am working on one dapp project and it was working well with metamask. I was using web3 modal for wallet connect.
After I installed blockwallet, metamask option disappeared and blockwallet appeared in the position of metamask before.
So I connected with blockwallet and I got below errors in the console window and the site stoped working.

https://prnt.sc/5QMcHWe6Y-an

I tired it on other browsers and ip addresses, but only on windows.
Please help me what I was wrong and how can I get rid of this bug.
Or is there any option that I can keep metamask and blockwallet together?
Thanks in advance.

Site link: https://mex-exchange.vercel.app/#
![Screenshot_103](https://user-images.githubusercontent.com/112295781/205566183-35693a10-38f6-430a-8de9-fbc7b08d69c5.png)

**Comment by julianariel** [comment]
hey @ryptodevc , thanks for your submission!

From what we see in your report, your dApp is trying to fetch a not supported block range. As seen in the screenshots, the requests are returning this message:

`eth_getLogs and eth_newFilter are limited to a 10,000 blocks range`

This is a limitation of our node providers and we cannot ensure that it'll work because we use more than one and switch them according to traffic along other variables. I suggest you take a look at that range and try to adjust your dApp requests to fit the limitation if it works for you.

Otherwise, in order to keep any other web3 wallet along with BlockWallet, we provide the "Default Browser Wallet" flag. You can check [this article](https://help.blockwallet.io/hc/en-us/articles/4672446037905-Setting-BlockWallet-as-your-Default-Browser-Wallet) that explains how to modify this setting and achieve what you're looking for.

Hope everything is clear for you.

Thanks!
