### ISSUE TITLE
Failed to connect wallet

### ISSUE THREAD

**Issue by AidenNguyen142** [block-wallet/extension#252]
I couldn't connect BlockWallet to https://rinkeby.orbiter.finance/ and https://labs.zetachain.com/swap.

[**Screenshots**](https://rinkeby.orbiter.finance/)
![image](https://user-images.githubusercontent.com/113259152/205568890-3f499966-ac64-4a38-8c5d-0ce4c5200931.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.95

**Comment by julianariel** [comment]
hey @AidenNguyen142 , thanks for your submission!

Both dApps you mention are forcing users to use MetaMask. About **Orbiter**, we're in touch with their team and we've already submitted a [Pull Request](https://github.com/Orbiter-Finance/OrbiterFE-V2/pull/9) in order to include BlockWallet's connect button. 

Regarding **Zetachain**, their dApp implements **RainbowKit** modal. We've contacted them recently too and submitted a [discussion](https://github.com/rainbow-me/rainbowkit/discussions/889) so they can add support for BlockWallet and hopefully we'll be receiving good news soon.

In case we don't have a solution soon from them, we will implement a workaround fix for these and keep you updated.

Thanks!

**Comment by AidenNguyen142** [comment]
Hey @julianariel, this is an FYI, I'm able to connect BlockWallet with https://rinkeby.orbiter.finance/

![image](https://user-images.githubusercontent.com/113259152/206510863-6625b255-9e6b-46bb-bcf8-6d0cf5b8faf5.png)

**Comment by julianariel** [comment]
hey @AidenNguyen142,

Luckily we managed to get included in Orbiter natively, as you mentioned, and we've also applied fixes to some other dApps compatibility on  BlockWallet's latest version, [v0.5.1](https://github.com/block-wallet/extension/releases/tag/v0.5.1). You should be able to connect to https://labs.zetachain.com/swap too now!

Thanks!
